language: minimal

services:
  - docker
  
jobs:
  include:
    - stage: build
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t alpine-dev .
      - docker images
      - docker tag alpine-dev $DOCKER_USERNAME/alpine
      - docker push $DOCKER_USERNAME/alpine
    - stage: test
      script: docker run --rm $DOCKER_USERNAME/alpine cat /etc/alpine-release 
