language: minimal

services:
  - docker

script:
  - docker build -t alpine-dev .
  - docker run alpine-dev cat /etc/alpine-release

after_script:
  - docker images
  - docker ps -a

before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
deploy:
  provider: script
  script: docker push $DOCKER_USERNAME/alpine
  on:
    branch: master
