version: 2.1

executors:
  my-executor:
    machine: true

jobs:
  clone:
    executor: my-executor
    steps:
      - checkout
      - persist_to_workspace

  build:
    executor: my-executor
    steps:
      - attach_workspace:
      - run: |
          docker build -t ${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME} .

  test:
    executor: my-executor
    steps:
      - run: |
          docker images

workflows:
  pipeline_alpine:
    jobs:
      - clone
      - build:
          requires:
            - clone
      - test:
          requires:
            - build
