name: docker build
on:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        alpine_tag:
          - 3.7
          - 3.8
          - 3.9
          - 3.10,latest
    runs-on: ubuntu-latest
    steps:
      - name: clone
        uses: actions/checkout@master
      - name: build
        env:
          alpine_tag: ${{matrix.alpine_tag}}
          owner: ${{github.event.repository.owner.name}}
          repo: ${{github.event.repository.name}}
        uses: actions/docker/cli@master
        with:
          args: build --build-arg ALPINE_TAG=${ALPINE_TAG%%,*} -t ${OWNER}/${REPO}-dev:${ALPINE_TAG%%,*} .
