name: docker build
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: clone
        uses: actions/checkout@master
      - name: test
        run: docker info
