name: docker build
on:
  push:
    branches:
      - master

jobs:
  Job1:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        alpine_tag:
          - 3.7
          - 3.8
          - 3.9
          - 3.10,latest
    steps:
      - name: clone
        uses: actions/checkout@master
      - name: build
        uses: triptixx/action-docker-build@master
        with:
          repo: alpine-dev
          build_args:
            - ALPINE_TAG=3.9
