name: docker build
on:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        alpine_tag:
          - 3.7
          - 3.8
          - 3.9
          - 3.10
    runs-on: ubuntu-latest
    steps:
      - name: clone
        uses: actions/checkout@master
      - name: build
        uses: actions/docker/cli@master
        with:
          args: build --build-arg ALPINE_TAG=${{matrix.alpine_tag}} -t ${{github.repository}}:${{matrix.alpine_tag}} .
