name: docker build
on:
  push:
    branches:
      - master

jobs:
  alpine:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        alpine_tag:
          - 3.7
          - 3.8
          - 3.9
          - 3.10
          - edge
    steps:
      - name: test
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "${{ matrix.alpine_tag }}"
